# Generated by Django 4.1.2 on 2022-11-30 13:35

#this file is automatically created once we create models and connect our db with mysql in settings.py

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),#id is created automatically in django
                #id will be the primary key - which is qunique in each row of a table
                ('name', models.CharField(max_length=250)),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
            ],
        ),
    ]
